// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDockerDiskSpace() {
  return window['go']['main']['App']['CheckDockerDiskSpace']();
}

export function CleanupDockerSystem() {
  return window['go']['main']['App']['CleanupDockerSystem']();
}

export function CreateFile(arg1, arg2) {
  return window['go']['main']['App']['CreateFile'](arg1, arg2);
}

export function DeleteFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteFile'](arg1, arg2);
}

export function DetectBestMode() {
  return window['go']['main']['App']['DetectBestMode']();
}

export function DuplicateFile(arg1, arg2) {
  return window['go']['main']['App']['DuplicateFile'](arg1, arg2);
}

export function ExportPDF() {
  return window['go']['main']['App']['ExportPDF']();
}

export function ExportSource() {
  return window['go']['main']['App']['ExportSource']();
}

export function GetBuildLog() {
  return window['go']['main']['App']['GetBuildLog']();
}

export function GetBuildStatus() {
  return window['go']['main']['App']['GetBuildStatus']();
}

export function GetCompilationMetrics() {
  return window['go']['main']['App']['GetCompilationMetrics']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetPDFContent() {
  return window['go']['main']['App']['GetPDFContent']();
}

export function GetPDFPath() {
  return window['go']['main']['App']['GetPDFPath']();
}

export function GetProject() {
  return window['go']['main']['App']['GetProject']();
}

export function GetRemoteCompilerHealth() {
  return window['go']['main']['App']['GetRemoteCompilerHealth']();
}

export function GetRendererConfig() {
  return window['go']['main']['App']['GetRendererConfig']();
}

export function GetRendererLogs() {
  return window['go']['main']['App']['GetRendererLogs']();
}

export function GetRendererStatus() {
  return window['go']['main']['App']['GetRendererStatus']();
}

export function GitCommit(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitCommit'](arg1, arg2, arg3);
}

export function GitPull(arg1) {
  return window['go']['main']['App']['GitPull'](arg1);
}

export function GitPush(arg1) {
  return window['go']['main']['App']['GitPush'](arg1);
}

export function GitStatus() {
  return window['go']['main']['App']['GitStatus']();
}

export function IsRemoteCompilerHealthy() {
  return window['go']['main']['App']['IsRemoteCompilerHealthy']();
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function MoveFile(arg1, arg2) {
  return window['go']['main']['App']['MoveFile'](arg1, arg2);
}

export function OpenProjectDialog() {
  return window['go']['main']['App']['OpenProjectDialog']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function ResetCompilationMetrics() {
  return window['go']['main']['App']['ResetCompilationMetrics']();
}

export function RestartRenderer() {
  return window['go']['main']['App']['RestartRenderer']();
}

export function SetCompilerConfig(arg1, arg2) {
  return window['go']['main']['App']['SetCompilerConfig'](arg1, arg2);
}

export function SetImageSource(arg1, arg2) {
  return window['go']['main']['App']['SetImageSource'](arg1, arg2);
}

export function SetProject(arg1) {
  return window['go']['main']['App']['SetProject'](arg1);
}

export function SetRendererAutoStart(arg1) {
  return window['go']['main']['App']['SetRendererAutoStart'](arg1);
}

export function SetRendererMode(arg1) {
  return window['go']['main']['App']['SetRendererMode'](arg1);
}

export function SetRendererPort(arg1) {
  return window['go']['main']['App']['SetRendererPort'](arg1);
}

export function SetRendererRemoteToken(arg1) {
  return window['go']['main']['App']['SetRendererRemoteToken'](arg1);
}

export function SetRendererRemoteURL(arg1) {
  return window['go']['main']['App']['SetRendererRemoteURL'](arg1);
}

export function StartRenderer() {
  return window['go']['main']['App']['StartRenderer']();
}

export function StopRenderer() {
  return window['go']['main']['App']['StopRenderer']();
}

export function SyncTeXEdit(arg1, arg2, arg3) {
  return window['go']['main']['App']['SyncTeXEdit'](arg1, arg2, arg3);
}

export function SyncTeXView(arg1, arg2, arg3) {
  return window['go']['main']['App']['SyncTeXView'](arg1, arg2, arg3);
}

export function TriggerBuild(arg1, arg2, arg3) {
  return window['go']['main']['App']['TriggerBuild'](arg1, arg2, arg3);
}

export function VerifyCustomImage(arg1) {
  return window['go']['main']['App']['VerifyCustomImage'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
