/// <reference path="./wails.d.ts" />
import { AuthState, AuthUser } from "./auth";
import { BuildStatus, CompilationMetrics } from "./build";
import { Config } from "./config";
import { FileContent, FileEntry } from "./file";
import { GitStatus } from "./git";
import { ProjectInfo } from "./project";
import { RemoteCompilerHealth, RendererConfig, RendererStatus } from "./renderer";
import { SyncTeXResult } from "./synctex";

export interface WailsApp {
  CheckDockerDiskSpace(): Promise<number>;
  CleanupDockerSystem(): Promise<void>;
  CreateFile(path: string, type: string): Promise<void>;
  DeleteFile(path: string, recursive: boolean): Promise<void>;
  DetectBestMode(): Promise<string>;
  DuplicateFile(from: string, to: string): Promise<void>;
  ExportPDF(): Promise<string>;
  ExportSource(): Promise<string>;
  GetAuthSignInURL(): Promise<string>;
  GetAuthSignUpURL(): Promise<string>;
  GetAuthState(): Promise<AuthState>;
  GetAuthUser(): Promise<AuthUser>;
  GetBuildLog(): Promise<string>;
  GetBuildStatus(): Promise<BuildStatus>;
  GetCompilationMetrics(): Promise<CompilationMetrics>;
  GetConfig(): Promise<Config>;
  GetPDFContent(): Promise<string>;
  GetPDFPath(): Promise<string>;
  GetProject(): Promise<ProjectInfo>;
  GetRemoteCompilerHealth(): Promise<RemoteCompilerHealth>;
  GetRendererConfig(): Promise<RendererConfig>;
  GetRendererLogs(): Promise<string>;
  GetRendererStatus(): Promise<RendererStatus>;
  GetSessionToken(): Promise<string>;
  GitCommit(message: string, files: string[], all: boolean): Promise<void>;
  GitPull(remote: string): Promise<void>;
  GitPush(remote: string): Promise<void>;
  GitStatus(): Promise<GitStatus>;
  HandleAuthCallback(url: string): Promise<void>;
  HandleAuthCallbackWithUser(userId: string, email: string, firstName: string, lastName: string): Promise<void>;
  IsAuthenticated(): Promise<boolean>;
  IsRemoteCompilerHealthy(): Promise<boolean>;
  ListFiles(path: string): Promise<FileEntry[]>;
  MoveFile(from: string, toDir: string): Promise<void>;
  OpenAuthURL(): Promise<void>;
  OpenProjectDialog(): Promise<ProjectInfo>;
  ReadFile(path: string): Promise<FileContent>;
  RenameFile(from: string, to: string): Promise<void>;
  ResetCompilationMetrics(): Promise<void>;
  RestartRenderer(): Promise<void>;
  SetAuthUser(id: string, email: string, firstName: string): Promise<void>;
  SetCompilerConfig(url: string, token: string): Promise<void>;
  SetImageSource(source: string, ref: string): Promise<void>;
  SetProject(root: string): Promise<ProjectInfo>;
  SetRendererAutoStart(enabled: boolean): Promise<void>;
  SetRendererMode(mode: string): Promise<void>;
  SetRendererPort(port: number): Promise<void>;
  SetRendererRemoteToken(token: string): Promise<void>;
  SetRendererRemoteURL(url: string): Promise<void>;
  SignOut(): Promise<void>;
  StartRenderer(): Promise<void>;
  StopRenderer(): Promise<void>;
  SyncTeXEdit(page: number, x: number, y: number): Promise<SyncTeXResult>;
  SyncTeXView(file: string, line: number, col: number): Promise<SyncTeXResult>;
  TriggerBuild(mainFile: string, engine: string, shellEscape: boolean): Promise<void>;
  VerifyCustomImage(path: string): Promise<boolean>;
  WriteFile(path: string, content: string): Promise<void>;
}