// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateFile(arg1:string,arg2:string):Promise<void>;

export function DeleteFile(arg1:string,arg2:boolean):Promise<void>;

export function DuplicateFile(arg1:string,arg2:string):Promise<void>;

export function ExportPDF():Promise<string>;

export function ExportSource():Promise<string>;

export function GetBuildLog():Promise<string>;

export function GetBuildStatus():Promise<main.BuildStatus>;

export function GetConfig():Promise<main.Config>;

export function GetPDFPath():Promise<string>;

export function GetProject():Promise<main.ProjectInfo>;

export function GitCommit(arg1:string,arg2:Array<string>,arg3:boolean):Promise<void>;

export function GitPull(arg1:string):Promise<void>;

export function GitPush(arg1:string):Promise<void>;

export function GitStatus():Promise<main.GitStatus>;

export function ListFiles(arg1:string):Promise<Array<main.FileEntry>>;

export function MoveFile(arg1:string,arg2:string):Promise<void>;

export function OpenProjectDialog():Promise<main.ProjectInfo>;

export function ReadFile(arg1:string):Promise<string>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function SetBuilderConfig(arg1:string,arg2:string):Promise<void>;

export function SetProject(arg1:string):Promise<main.ProjectInfo>;

export function SyncTeXEdit(arg1:number,arg2:number,arg3:number):Promise<main.SyncTeXResult>;

export function SyncTeXView(arg1:string,arg2:number,arg3:number):Promise<main.SyncTeXResult>;

export function TriggerBuild(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
