// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckDockerDiskSpace():Promise<number>;

export function CleanupDockerSystem():Promise<void>;

export function CreateFile(arg1:string,arg2:string):Promise<void>;

export function DeleteFile(arg1:string,arg2:boolean):Promise<void>;

export function DetectBestMode():Promise<string>;

export function DuplicateFile(arg1:string,arg2:string):Promise<void>;

export function ExportPDF():Promise<string>;

export function ExportSource():Promise<string>;

export function GetAuthSignInURL():Promise<string>;

export function GetAuthSignUpURL():Promise<string>;

export function GetAuthState():Promise<main.AuthState>;

export function GetAuthUser():Promise<main.AuthUser>;

export function GetBuildLog():Promise<string>;

export function GetBuildStatus():Promise<main.BuildStatus>;

export function GetCompilationMetrics():Promise<main.CompilationMetrics>;

export function GetConfig():Promise<main.Config>;

export function GetPDFContent():Promise<string>;

export function GetPDFPath():Promise<string>;

export function GetProject():Promise<main.ProjectInfo>;

export function GetRemoteCompilerHealth():Promise<main.RemoteCompilerHealth>;

export function GetRendererConfig():Promise<main.RendererConfig>;

export function GetRendererLogs():Promise<string>;

export function GetRendererStatus():Promise<main.RendererStatus>;

export function GetSessionToken():Promise<string>;

export function GitCommit(arg1:string,arg2:Array<string>,arg3:boolean):Promise<void>;

export function GitPull(arg1:string):Promise<void>;

export function GitPush(arg1:string):Promise<void>;

export function GitStatus():Promise<main.GitStatus>;

export function HandleAuthCallback(arg1:string):Promise<void>;

export function IsAuthenticated():Promise<boolean>;

export function IsRemoteCompilerHealthy():Promise<boolean>;

export function ListFiles(arg1:string):Promise<Array<main.FileEntry>>;

export function MoveFile(arg1:string,arg2:string):Promise<void>;

export function OpenAuthURL():Promise<void>;

export function OpenProjectDialog():Promise<main.ProjectInfo>;

export function ReadFile(arg1:string):Promise<main.FileContent>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function ResetCompilationMetrics():Promise<void>;

export function RestartRenderer():Promise<void>;

export function SetImageSource(arg1:string,arg2:string):Promise<void>;

export function SetProject(arg1:string):Promise<main.ProjectInfo>;

export function SetRemoteCompilerURL(arg1:string):Promise<void>;

export function SetRendererAutoStart(arg1:boolean):Promise<void>;

export function SetRendererMode(arg1:string):Promise<void>;

export function SetRendererPort(arg1:number):Promise<void>;

export function SignOut():Promise<void>;

export function StartRenderer():Promise<void>;

export function StopRenderer():Promise<void>;

export function SyncTeXEdit(arg1:number,arg2:number,arg3:number):Promise<main.SyncTeXResult>;

export function SyncTeXView(arg1:string,arg2:number,arg3:number):Promise<main.SyncTeXResult>;

export function TriggerBuild(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function VerifyCustomImage(arg1:string):Promise<boolean>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
